repos:
-   repo: https://github.com/ParisNeo/parisneo-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: parisneo-python-check  # For Python projects
    -   id: parisneo-js-check      # For JavaScript projects